//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EID { get; set; }
        public string Ename { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EDOJ { get; set; }
        public string Edesignation { get; set; }
        public string Edept { get; set; }
        public string Ecity { get; set; }
    }
}
